# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('proxyId', models.IntegerField(primary_key=True, serialize=False, verbose_name='代理ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('port', models.CharField(max_length=10, verbose_name='端口号')),
                ('country', models.CharField(max_length=255, verbose_name='国家')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '代理ip',
                'db_table': 'ip',
            },
        ),
    ]
