# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0003_auto_20190808_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logId', models.IntegerField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('logDetail', models.CharField(max_length=512, verbose_name='日志详情')),
                ('taskId', models.CharField(max_length=50, verbose_name='任务ID')),
                ('level', models.CharField(max_length=20, verbose_name='错误级别')),
                ('url', models.CharField(max_length=256, verbose_name='发生错误URL')),
                ('spiderName', models.CharField(max_length=256, verbose_name='spider名字')),
                ('extInfo', models.TextField(null=True, verbose_name='预留字段')),
            ],
            options={
                'verbose_name_plural': '抓取日志',
                'db_table': 'Log',
            },
        ),
    ]
