# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0005_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='图片ID'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='picKey',
            field=models.CharField(max_length=256, verbose_name='上传到CDN上的key'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='picPath',
            field=models.CharField(max_length=256, verbose_name='图片在本机路径'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='picUrl',
            field=models.CharField(max_length=256, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='picUrlMd5',
            field=models.CharField(max_length=256, verbose_name='图片链接MD5值'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='spiderName',
            field=models.CharField(max_length=256, verbose_name='spider名字'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='taskId',
            field=models.CharField(max_length=20, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
