# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0006_auto_20190808_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20, verbose_name='发生错误所在机器'),
        ),
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
