# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0007_auto_20190808_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='任务执行优先级'),
        ),
    ]
