# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-09 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0008_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='任务id'),
        ),
    ]
