# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0011_auto_20190809_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='扩展属性'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskRet',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='任务执行结果'),
        ),
    ]
