# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0012_auto_20190809_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': '抓取任务'},
        ),
        migrations.AddField(
            model_name='task',
            name='sourceUrls',
            field=models.TextField(null=True, verbose_name='配置详情链接'),
        ),
    ]
