# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0013_auto_20190810_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='startUrls',
            field=models.TextField(default='空', null=True, verbose_name='配置入口链接'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sourceUrls',
            field=models.TextField(default='空', null=True, verbose_name='配置详情链接'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskIP',
            field=models.CharField(default='0.0.0.0', editable=False, max_length=255, verbose_name='任务执行时主机ip'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(default='new', editable=False, max_length=255, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskType',
            field=models.CharField(choices=[('spider', '全量抓取'), ('spider_update', '部分抓取')], default='全量抓取', max_length=255, verbose_name='任务类型'),
        ),
    ]
