# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-10 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0014_auto_20190810_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra',
            field=models.CharField(default='空', editable=False, max_length=255, verbose_name='扩展属性'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskRet',
            field=models.CharField(default='空', editable=False, max_length=255, verbose_name='任务执行结果'),
        ),
    ]
