# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0015_auto_20190810_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxyId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='代理ID'),
        ),
    ]
