# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0017_auto_20191001_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, verbose_name='用户Id')),
                ('userName', models.CharField(max_length=255, verbose_name='用户名')),
                ('sex', models.CharField(choices=[('0', '男'), ('1', '女')], default='男', max_length=255, verbose_name='性别')),
                ('phone', models.CharField(default='110', max_length=255, verbose_name='手机号')),
                ('age', models.IntegerField(default=22)),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
    ]
