# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0020_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='歌单Id'),
        ),
    ]
