# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0021_auto_20200207_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recder',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户Id')),
                ('songId', models.CharField(max_length=255, verbose_name='已收听歌曲Id')),
                ('songTag', models.CharField(max_length=255, verbose_name='歌曲分类')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '收听记录表',
                'db_table': 'recder',
            },
        ),
    ]
