# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0022_recder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recder',
            name='songName',
            field=models.CharField(default='', max_length=255, verbose_name='曲名'),
        ),
    ]
