# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0023_recder_songname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecRet',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户Id')),
                ('songIdList', models.CharField(max_length=255, verbose_name='已收听歌曲Id')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '推介结果表',
                'db_table': 'recret',
            },
        ),
    ]
