# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0024_recret'),
    ]

    operations = [
        migrations.AddField(
            model_name='recret',
            name='isReced',
            field=models.CharField(default='否', max_length=1, verbose_name='是否被推介过'),
        ),
    ]
