# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0026_auto_20200208_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='recret',
            name='songName',
            field=models.CharField(default='', max_length=255, verbose_name='曲名'),
        ),
    ]
