# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0028_auto_20200208_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recret',
            name='createTime',
        ),
    ]
