# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0029_remove_recret_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecderAlter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=255, verbose_name='用户Id')),
                ('songId', models.CharField(max_length=255, verbose_name='已收听歌曲Id')),
                ('songTag', models.CharField(max_length=255, verbose_name='歌曲分类')),
                ('songName', models.CharField(default='', max_length=255, verbose_name='曲名')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '收听记录表',
                'db_table': 'recderalter',
            },
        ),
        migrations.CreateModel(
            name='RecRetAlter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=255, verbose_name='用户Id')),
                ('songId', models.CharField(max_length=255, verbose_name='歌曲Id')),
                ('songName', models.CharField(default='', max_length=255, verbose_name='曲名')),
                ('source', models.CharField(default='热歌推介', max_length=255, verbose_name='推介来源')),
                ('isReced', models.CharField(default='否', max_length=1, verbose_name='是否被推介过')),
            ],
            options={
                'verbose_name_plural': '推介结果表',
                'db_table': 'recretalter',
            },
        ),
        migrations.DeleteModel(
            name='Recder',
        ),
        migrations.DeleteModel(
            name='RecRet',
        ),
    ]
